#!/bin/bash
current_dir=$(pwd) # Get current directory
Xammp_dir="/opt/lampp/" #Xammp location 
# functions
check_xampp_installed() {
    if [ ! -d "$Xammp_dir" ]; then
        echo "XAMPP is not installed."
        exit 1
    fi
}
ftpSelected() {
if [ $ftp = true ]
then
if [[ $on = true ]]
   then
       sudo ./xampp startftp
   elif [[ $off = true ]]
   then
       sudo ./xampp stopftp 
   fi
fi
}
dbSelected() {
if [ $db = true ]
then
if [[ $on = true ]]
   then
       sudo ./xampp startmysql
   elif [[ $off = true ]]
   then
       sudo ./xampp stopmysql 
   fi
fi
}
allSelected() {
if [ $all = true ]
then
if [[ $on = true ]]
   then
    sudo ./xampp startapache
    sudo ./xampp startmysql
    sudo ./xampp startftp
   elif [[ $off = true ]]
   then
    sudo ./xampp stopapache
    sudo ./xampp stopmysql   
    sudo ./xampp stopftp   
    fi
fi
}
apacheSelected() {
#Check if apache selected
if [ $apch = true ]
 then
#echo "Apache selected"
if [[ $on = true ]]
   then
      sudo ./xampp startapache
   elif [[ $off = true ]]
   then
       sudo ./xampp stopapache
   fi
fi
}
# end functions 
check_xampp_installed # check if xammp installed 
if [ "$#" -lt 1 ]; then
   echo "Usage: $0 [Service] <Action>"
   echo "Service:
  gui                 Start the gui
  apch                Select Apache
  db                  Select Database (MariadDB)
  ftp                 Select ProFTPD
  all                 Select  apache ftp & database
  h                   List all xampp commands
  "
  echo "Action:
  on                  Turn on the service/services
  off                 Turn off the service/services
  "
  exit 1
fi
# Assign the arguments to variables and lowercase
arg1=$(echo "$1" | tr '[:upper:]' '[:lower:]')
arg2=$(echo "$2" | tr '[:upper:]' '[:lower:]')
#Vars
all=null
apch=null
db=null
ftp=null
off=null
on=null
cd $Xammp_dir
#Check arg1
case $arg1 in
   gui)
       sudo ./manager-linux-x64.run
       exit 1
       ;;
    h)
       sudo ./xampp panel
       exit 1
       ;;
   apch)
       apch=true
       ;;
   db)
       db=true
       ;;
    ftp)
       ftp=true
       ;;
   all)
       all=true
       ;;
   *)
       echo "Error...Retry"
       ;;
esac
#Check arg2
case $arg2 in
   on)
       on=true
       ;;
   off)
       off=true
       ;;
   *)
       echo "Error...Retry"
       ;;
esac
allSelected
apacheSelected
dbSelected
ftpSelected
cd $current_dir
